// Part of the ui design-system, split out of the former monolithic ui.tsx.
// All symbols are re-exported from ./index so call sites still import from
// "@/components/ui".

import { StyleSheet } from "react-native";
import { radius, spacing } from "@/theme";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 48,
    paddingVertical: spacing.sm,
  },
  topBarRight: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  topBarBadge: {
    position: "absolute",
    top: -5,
    right: -7,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarBadgeText: { color: "#ffffff", fontSize: 10, fontWeight: "800" },
  topBarLogo: { width: 88, height: 30 },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingTop: spacing.sm + 2,
    gap: spacing.sm,
  },
  tabLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 4,
  },
  tabText: { fontSize: 13.5, letterSpacing: -0.1 },
  tabIndicator: { height: 2.5, alignSelf: "stretch" },
  tabIndicatorBar: {
    position: "absolute",
    left: 0,
    bottom: 0,
    height: 2.5,
    borderRadius: 2,
  },
  tabBadge: {
    borderRadius: radius.full,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBadgeText: { color: "#ffffff", fontSize: 11, fontWeight: "800" },
  floatingYearPicker: { position: "absolute", right: spacing.lg, bottom: spacing.md },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    // Tight top padding so the back/title row sits close to the top of the screen.
    paddingTop: spacing.sm,
    paddingBottom: 48,
    gap: spacing.md,
    maxWidth: 720,
    width: "100%",
    alignSelf: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginTop: 0,
    marginBottom: spacing.sm,
  },
  headerText: { flex: 1 },
  headerBack: { marginLeft: -6, justifyContent: "center" },
  card: {
    borderRadius: radius.lg,
    padding: spacing.lg + 2,
    gap: spacing.sm + 2,
  },
  sectionTitle: { marginTop: spacing.md, marginBottom: -2 },
  row: { flexDirection: "row", gap: spacing.sm, flexWrap: "wrap", alignItems: "center" },
  rowSpread: { flexDirection: "row", gap: spacing.sm, alignItems: "center" },
  rowLoading: { minHeight: 42, alignItems: "center", justifyContent: "center" },
  yearPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: radius.full,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  yearPillText: { fontWeight: "700", fontSize: 15 },
  // Pill buttons, matching the web app's rounded SOW styling.
  btn: {
    paddingHorizontal: spacing.xl,
    paddingVertical: 11,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
  },
  btnText: { fontWeight: "700", fontSize: 14, letterSpacing: -0.1 },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBadgeText: { color: "#ffffff", fontSize: 10, fontWeight: "800" },
  field: { gap: 6 },
  input: {
    borderRadius: radius.md,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    minHeight: 46,
  },
  inputRow: {
    borderRadius: radius.md,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  inputInner: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 11,
  },
  inputMultiline: { minHeight: 88, textAlignVertical: "top" },
  selectFace: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  optionSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingLeft: spacing.xl,
    paddingRight: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
  },
  optionSheetClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  optionList: { paddingHorizontal: spacing.md, paddingBottom: spacing.lg, gap: 2 },
  // Single uniform padding layer for dialog content (no compounding) — sides and
  // bottom match the title's horizontal inset; top adds to the title's gap.
  confirmContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    // Tight bottom inset so the message sits close to the footer actions.
    paddingBottom: spacing.md,
    gap: 14,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 13,
    borderRadius: radius.md,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipDot: { width: 6, height: 6, borderRadius: 3 },
  chipText: { fontSize: 11.5, fontWeight: "700", letterSpacing: 0.2 },
  error: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  empty: {
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.xl,
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xs,
  },
  emptyMessage: { textAlign: "center", lineHeight: 18 },
  // Fills the available space and centres the spinner so page-level loaders sit
  // in the middle of the screen. The minHeight keeps it visible if a parent
  // doesn't give it room to grow.
  loading: {
    flex: 1,
    minHeight: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallback: { alignItems: "center", justifyContent: "center" },
  segmented: {
    flexDirection: "row",
    borderRadius: radius.full,
    padding: 4,
  },
  segmentIndicator: {
    position: "absolute",
    top: 4,
    bottom: 4,
    left: 4,
    borderRadius: radius.full,
  },
  segment: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    borderRadius: radius.full,
    paddingVertical: 9,
    paddingHorizontal: 6,
  },
  segmentText: { fontSize: 13, fontWeight: "600", letterSpacing: -0.1 },
  segmentBadge: {
    borderRadius: radius.full,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentBadgeText: { color: "#ffffff", fontSize: 11, fontWeight: "800" },
  dialogOuter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.xl,
  },
  dialog: {
    borderRadius: radius.xl,
    width: "100%",
    maxWidth: 480,
    // Cap well below full height so there's always a clear backdrop area to
    // tap out, and the dialog never feels like it covers the whole screen.
    maxHeight: "70%",
    overflow: "hidden",
    flexDirection: "column",
  },
  sheetScroll: { flexShrink: 1 },
  sheetContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    // Bottom padding matches the top so the body is evenly inset (was a much
    // larger pad, plus extra when a footer existed). The footer below provides
    // its own spacing.
    paddingBottom: spacing.sm,
    gap: spacing.sm + 2,
  },
  sheetFooter: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
  },
  toast: {
    position: "absolute",
    bottom: 28,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  toastText: { fontWeight: "700", fontSize: 13 },
  footerWrap: {
    position: "absolute",
    bottom: spacing.md,
    paddingHorizontal: spacing.lg,
    maxWidth: 720,
    width: "100%",
    alignSelf: "center",
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  footerNote: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginBottom: spacing.sm,
  },
  footerInfoBtn: {
    width: 50,
    height: 50,
    borderRadius: radius.lg - 2,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  footerAction: {
    height: 50,
    borderRadius: radius.lg - 2,
    alignItems: "center",
    justifyContent: "center",
  },
  footerActionText: { fontSize: 16, fontWeight: "700", letterSpacing: -0.2 },
});
